language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO_VERSION=1.4.19
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.4

matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.19

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install selenium
  - pip install .

script: cd tests && make tests
