language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.7.4
  - DJANGO_VERSION=1.8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: 
  - if [ $DJANGO_VERSION == 1.8 ]; then pip install git+https://github.com/django/django.git@stable/1.8.x; else pip install -q Django==$DJANGO_VERSION; fi
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q selenium
  - pip install .

before_script: cd tests

script: make coverage

after_script: coveralls
