sudo: required
dist: trusty
language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.7.4
  - DJANGO_VERSION=1.8.1
  - DJANGO_VERSION=1.9.12

install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q selenium
  - pip install .

before_script:
  - sudo apt-get install -qq chromium-chromedriver
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd tests

script: make coverage

after_script: coveralls
