language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.7.4

#matrix:
#  exclude:
#    - python: 3.3
#      env: DJANGO_VERSION=1.4.19

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install selenium
  - pip install .

before_script: cd tests

script: make tests
